// Code generated by options-gen qa-version. DO NOT EDIT.

package client

import (
	fmt461e464ebed9 "fmt"
	"log/slog"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from func
	defaultOpts := getDefaultOptions()
	o.logger = defaultOpts.logger
	o.serviceUrl = defaultOpts.serviceUrl
	o.httpClient = defaultOpts.httpClient
	o.serviceToken = defaultOpts.serviceToken
	o.tracerProvider = defaultOpts.tracerProvider
	o.propagator = defaultOpts.propagator
	o.name = defaultOpts.name

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithLogger(opt *slog.Logger) OptOptionsSetter {
	return func(o *Options) { o.logger = opt }
}

func WithServiceUrl(opt string) OptOptionsSetter {
	return func(o *Options) { o.serviceUrl = opt }
}

func WithHttpClient(opt IHttpClient) OptOptionsSetter {
	return func(o *Options) { o.httpClient = opt }
}

func WithServiceToken(opt string) OptOptionsSetter {
	return func(o *Options) { o.serviceToken = opt }
}

func WithTracerProvider(opt TracerProvider) OptOptionsSetter {
	return func(o *Options) { o.tracerProvider = opt }
}

func WithPropagator(opt Propagator) OptOptionsSetter {
	return func(o *Options) { o.propagator = opt }
}

// The client name that used by instrumentation.
func WithName(opt string) OptOptionsSetter {
	return func(o *Options) { o.name = opt }
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	errs.Add(errors461e464ebed9.NewValidationError("serviceUrl", _validate_Options_serviceUrl(o)))
	errs.Add(errors461e464ebed9.NewValidationError("httpClient", _validate_Options_httpClient(o)))
	errs.Add(errors461e464ebed9.NewValidationError("tracerProvider", _validate_Options_tracerProvider(o)))
	errs.Add(errors461e464ebed9.NewValidationError("propagator", _validate_Options_propagator(o)))
	errs.Add(errors461e464ebed9.NewValidationError("name", _validate_Options_name(o)))
	return errs.AsError()
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_serviceUrl(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.serviceUrl, "required,url"); err != nil {
		return fmt461e464ebed9.Errorf("field `serviceUrl` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_httpClient(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.httpClient, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `httpClient` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_tracerProvider(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.tracerProvider, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `tracerProvider` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_propagator(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.propagator, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `propagator` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_name(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.name, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `name` did not pass the test: %w", err)
	}
	return nil
}
